- name: Create list directory
  file:
    path: "/etc/exim4/lists"
    state: directory
    owner: root
    group: Debian-exim

- name: Create lists domains
  file:
    path: "/etc/exim4/lists/{{ item.domain }}"
    state: directory
    owner: root
    group: Debian-exim
  with_items: "{{ exim4__listconf }}"
  when:
    - exim4__listconf is defined

- name: Create lists domains mailinglists
  include_tasks: configure_mailinglist_domain.yml
  loop: "{{ exim4__listconf }}"
  loop_control:
    loop_var: main_item
  when:
    - exim4__listconf is defined

- name: Setup exim4 main file for mm3
  template:
    src: 25_mm3_macros
    dest: /etc/exim4/conf.d/main/25_mm3_macros
    mode: 0644
    owner: root
    group: Debian-exim
  notify: Reload exim4

- name: Setup exim4 router file for mm3
  template:
    src: 155_mm3_router
    dest: /etc/exim4/conf.d/router/155_mm3_router
    mode: 0644
    owner: root
    group: Debian-exim
  notify: Reload exim4

- name: Setup exim4 transport file for mm3
  template:
    src: 55_mm3_transport
    dest: /etc/exim4/conf.d/transport/55_mm3_transport
    mode: 0644
    owner: root
    group: Debian-exim
  notify: Reload exim4
