---
# Called by main.yml
- name: MySQL/MariaDB user create
  mysql_user:
    name: "{{ exim4__db_conf.user }}"
    password: "{{ exim4__db_conf.password }}"
    priv: "{{ exim4__db_conf.name }}.*:ALL,GRANT"
    host: "%"
    login_user: "{{ exim4__db_conf.admin_user }}"
    login_password: "{{ exim4__db_conf.admin_password }}"
    login_host: "{{ exim4__db_conf.hostname }}"

- name: MySQL/MariaDB alias db create
  mysql_db:
    name: "{{ exim4__db_conf.name }}"
    login_user: "{{ exim4__db_conf.admin_user }}"
    login_password: "{{ exim4__db_conf.admin_password }}"
    login_host: "{{ exim4__db_conf.hostname }}"

- name: MySQL/MariaDB populate alias file setup
  copy:
    src: initial_alias_table.sql
    dest: /tmp/initial_alias_table.sql

- name: MySQL/MariaDB populate pwd file setup
  copy:
    src: initial_pwd_table.sql
    dest: /tmp/initial_pwd_table.sql

- name: MySQL/MariaDB populate domain file setup
  copy:
    src: initial_domain_table.sql
    dest: /tmp/initial_domain_table.sql

- name: MySQL/MariaDB alias db initial populate
  mysql_db:
    name: "{{ exim4__db_conf.name }}"
    state: import
    target: /tmp/initial_alias_table.sql

    login_user: "{{ exim4__db_conf.admin_user }}"
    login_password: "{{ exim4__db_conf.admin_password }}"
    login_host: "{{ exim4__db_conf.hostname }}"

- name: MySQL/MariaDB pwd db initial populate
  mysql_db:
    name: "{{ exim4__db_conf.name }}"
    state: import
    target: /tmp/initial_pwd_table.sql

    login_user: "{{ exim4__db_conf.admin_user }}"
    login_password: "{{ exim4__db_conf.admin_password }}"
    login_host: "{{ exim4__db_conf.hostname }}"

- name: MySQL/MariaDB domain db initial populate
  mysql_db:
    name: "{{ exim4__db_conf.name }}"
    state: import
    target: /tmp/initial_domain_table.sql

    login_user: "{{ exim4__db_conf.admin_user }}"
    login_password: "{{ exim4__db_conf.admin_password }}"
    login_host: "{{ exim4__db_conf.hostname }}"

- name: Setup main file for sql servers
  template:
    src: main_30_exim4-config_mysql_servers
    dest: /etc/exim4/conf.d/main/30_exim4-config_mysql_servers
    mode: 0640
  notify: Reload exim4


- name: Setup specific router for virtual domains aliases
  template:
    src: router_103_exim4-config_virtual_domain_aliases_db
    dest: /etc/exim4/conf.d/router/103_exim4-config_virtual_domain_aliases_db
  notify: Reload exim4
