---
# Called by main.yml
- name: Setup specific router for virtual domains aliases
  template:
    src: router_105_exim4-config_virtual_domain_aliases
    dest: /etc/exim4/conf.d/router/105_exim4-config_virtual_domain_aliases
  notify: Reload exim4
