---
# Install the package
- name: Install package
  apt:
    name: "{{ exim4__default_packages }}"
    update_cache: yes
    state: present
  when:
    - exim4__install

- name: Install db package
  apt:
    name: "{{ exim4__db_aliases_default_packages }}"
    update_cache: yes
    state: present
  when:
    - exim4__install
    - exim4__use_db_aliases|default(False)

# Create config file
- name: Update global aliases
  lineinfile:
    regexp: "^root:.*"
    line: "root: {{ exim4__root_email }}"
    path: /etc/aliases
  when:
    - exim4__configure
    - exim4__root_email is defined
  notify: Reload aliases
  ignore_errors: yes

- name: Setup update-exim4.conf.conf
  template:
    src: update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf
  when:
    - exim4__configure
  notify: Reload exim4

- name: Setup hubbed_hosts file
  template:
    src: hubbed_hosts
    dest: /etc/exim4/hubbed_hosts
    mode: 0644
    owner: root
    group: Debian-exim
  when:
    - exim4__configure
    - exim4__conf_hubbed is defined

- name: Remove hubbed_hosts file
  file:
    dest: /etc/exim4/hubbed_hosts
    state: absent
  when:
    - exim4__configure
    - exim4__conf_hubbed is not defined

- name: Fix hubbed_hosts router
  lineinfile:
    regexp: "^ *transport *= *remote_smtp$"
    line: "  transport = remote_smtp_smarthost"
    path: /etc/exim4/conf.d/router/150_exim4-config_hubbed_hosts
  notify: Reload exim4
  when:
    - exim4__configure
    - exim4__conf_hubbed is defined
    - exim4__conf_split

- name: Fix TLS check
  template:
    src: main_00_local_settings
    dest: /etc/exim4/conf.d/main/00_local_settings
  notify: Reload exim4
  when:
    - exim4__configure
    - exim4__avoid_TLS_check|default(False)

- name: Warn about hubbed_hosts config
  debug:
    msg: "Don't know how to manage hubbed_host router on a non-split config !"
  when:
    - exim4__configure
    - exim4__conf_hubbed is defined
    - not exim4__conf_split

- name: Setup passwd.client file
  template:
    src: passwd.client
    dest: /etc/exim4/passwd.client
    mode: 0640
    owner: root
    group: Debian-exim
  when:
    - exim4__configure
    - exim4__conf_remote is defined

- name: Remove passwd.client file
  file:
    dest: /etc/exim4/passwd.client
    state: absent
  when:
    - exim4__configure
    - exim4__conf_remote is not defined

- name: Set mailname file
  template:
    dest: /etc/mailname
    src: mailname
    owner: root
    group: root
    mode: 0644
  when:
    - exim4__configure

- import_tasks: configure_mailman.yml
  notify: Reload aliases
  when:
    - exim4__configure
    - exim4__use_mailman

- import_tasks: configure_spamassassin.yml
  when:
    - exim4__configure
    - exim4__use_spamassassin

- import_tasks: configure_virtual_mail.yml
  notify: Reload aliases
  when:
    - exim4__configure
    - exim4__use_virtual_mail

- import_tasks: configure_virtual_mail_aliases.yml
  notify: Reload aliases
  when:
    - exim4__configure
    - exim4__use_virtual_mail
    - exim4__use_file_aliases

- import_tasks: configure_virtual_mail_aliases_db.yml
  when:
    - exim4__configure
    - exim4__use_virtual_mail
    - exim4__use_db_aliases

- name: Create domain list file
  template:
    src: domain_list
    dest: /var/lib/mail/domain_list
    mode: 0660
    owner: Debian-exim
    group: Debian-exim
  when:
    - exim4__configure
    - exim4__host_virtual_mail

- name: Create domain directories
  file:
    path: /var/lib/mail/{{ item.name }}
    state: directory
    mode: 0755
    owner: Debian-exim
    group: Debian-exim
  loop: "{{ exim4__managed_domain }}"
  when:
    - exim4__configure
    - exim4__host_virtual_mail

- name: Create email_addresses for outgoing mail
  template:
    src: email_addresses
    dest: /etc/email-addresses
    mode: 0644
    owner: root
    group: root
  when:
    - exim4__configure
    - exim4__conf_email_addresses is defined

- include_tasks: create_domain_users.yml
  loop: "{{ exim4__managed_domain }}"
  when:
    - exim4__configure
    - exim4__host_virtual_mail
    - exim4__managed_domain is defined

- import_tasks: configure_mail_reader.yml
  when:
    - exim4__configure
    - exim4__use_mail_reader

- name: Set max smtp mail queue by connection
  template:
    src: main_02_exim4-config_max_smtp
    dest: /etc/exim4/conf.d/main/02_exim4-config_max_smtp
    mode: 0644
    owner: root
    group: root
  when:
    - exim4__configure
    - exim4__conf_split
    - exim4__max_smtp_queue is defined
  notify: Reload exim4

- name: Set rewriting rules if needed
  template:
    src: rewrite_31_exim4-config_rewriting
    dest: /etc/exim4/conf.d/rewrite/31_exim4-config_rewriting
    mode: 0644
    owner: root
    group: root
  when:
    - exim4__configure
    - exim4__conf_split
    - exim4__conf_rewrite is defined
  notify: Reload exim4

- name: Warn about exim4__max_smtp_queue config
  debug:
    msg: "Don't know how to manage exim4__max_smtp_queue router on a non-split config !"
  when:
    - exim4__configure
    - exim4__max_smtp_queue is defined
    - not exim4__conf_split
