---
# Install the package
- name: Install package
  apt:
    name: "{{ exim4__default_packages }}"
    update_cache: yes
    state: present
  when:
    - exim4__install

# Create config file
- name: Update global aliases
  lineinfile:
    regexp: "^root:.*"
    line: "root: {{ exim4__root_email }}"
    path: /etc/aliases
  when:
    - exim4__configure
    - exim4__root_email is defined
  notify: Reload aliases
  ignore_errors: yes

- name: Setup update-exim4.conf.conf
  template:
    src: update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf
  when:
    - exim4__configure
  notify: Reload exim4

- name: Setup hubbed_hosts file
  template:
    src: hubbed_hosts
    dest: /etc/exim4/hubbed_hosts
    mode: 0644
    owner: root
    group: Debian-exim
  when:
    - exim4__configure
    - exim4__conf_hubbed is defined

- name: Fix hubbed_hosts router
  lineinfile:
    regexp: "^ *transport *= *remote_smtp$"
    line: "  transport = remote_smtp_smarthost"
    path: /etc/exim4/conf.d/router/150_exim4-config_hubbed_hosts
  notify: Reload exim4
  when:
    - exim4__configure
    - exim4__conf_hubbed is defined

- name: Setup passwd.client file
  template:
    src: passwd.client
    dest: /etc/exim4/passwd.client
    mode: 0640
    owner: root
    group: Debian-exim
  when:
    - exim4__configure
    - exim4__conf_remote is defined

- name: Set mailname file
  template:
    dest: /etc/mailname
    src: mailname
    owner: root
    group: root
    mode: 0644
  when:
    - exim4__configure

- import_tasks: configure_mailman.yml
  notify: Reload aliases
  when:
    - exim4__configure
    - exim4__use_mailman

- import_tasks: configure_spamassassin.yml
  when:
    - exim4__configure
    - exim4__use_spamassassin

- import_tasks: configure_virtual_mail.yml
  notify: Reload aliases
  when:
    - exim4__configure
    - exim4__use_virtual_mail

- name: Create domain list file
  template:
    src: domain_list
    dest: /var/lib/mail/domain_list
    mode: 0660
    owner: Debian-exim
    group: Debian-exim
  when:
    - exim4__configure
    - exim4__host_virtual_mail

- name: Create domain directories
  file:
    path: /var/lib/mail/{{ item.name }}
    state: directory
    mode: 0755
    owner: Debian-exim
    group: Debian-exim
  loop: "{{ exim4__managed_domain }}"
  when:
    - exim4__configure
    - exim4__host_virtual_mail

- include_tasks: create_domain_users.yml
  loop: "{{ exim4__managed_domain }}"
  when:
    - exim4__configure
    - exim4__host_virtual_mail
    - exim4__managed_domain is defined

- import_tasks: configure_mail_reader.yml
  when:
    - exim4__configure
    - exim4__use_mail_reader

