---
# Install the package
- name: Install package
  apt:
    name: "{{ exim4__default_packages }}"
    update_cache: yes
    state: present
  when:
    - exim4__install

# Create config file
- name: Update global aliases
  lineinfile:
    regexp: "^root:.*"
    line: "root: {{ exim4__root_email }}"
    path: /etc/aliases
  when:
    - exim4__configure
  notify: Reload aliases
  ignore_errors: yes

- name: Setup update-exim4.conf.conf
  template:
    src: update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf
  when:
    - exim4__configure
  notify: Reload exim4

- name: Setup hubbed_hosts file
  template:
    src: hubbed_hosts
    dest: /etc/exim4/hubbed_hosts
    mode: 0644
    owner: root
    group: Debian-exim
  when:
    - exim4__configure
    - exim4__conf_hubbed is defined

- name: Fix hubbed_hosts router
  lineinfile:
    regexp: "^ *transport *= *remote_smtp$"
    line: "  transport = remote_smtp_smarthost"
    path: /etc/exim4/conf.d/router/150_exim4-config_hubbed_hosts
  notify: Reload exim4
  when:
    - exim4__configure
    - exim4__conf_hubbed is defined


- name: Setup passwd.client file
  template:
    src: passwd.client
    dest: /etc/exim4/passwd.client
    mode: 0640
    owner: root
    group: Debian-exim
  when:
    - exim4__configure
    - exim4__conf_remote is defined

- name: Set mailname file
  template:
    dest: /etc/mailname
    src: mailname
    owner: root
    group: root
    mode: 0644

- name: Install mailman package
  apt:
    name: "{{ exim4__mailman_default_packages }}"
    update_cache: yes
    state: present
  register: mailman_install
  when:
    - exim4__install
    - exim4__use_mailman

# Fresh install is consuming too much CPU on start (?)
- name: Urgently stop mailman3-web (if fresh install)
  systemd:
    name: mailman3-web
    state: stopped
  register: mailman_stopped
  when:
    - exim4__configure
    - exim4__use_mailman
    - mailman_install is changed

# - name: Reconfigure mailman3-web cronjobs
#   cron:

- import_tasks: configure_mailman.yml
  when:
    - exim4__configure
    - exim4__use_mailman

- import_tasks: configure_exim4_mailman.yml
  when:
    - exim4__configure
    - exim4__use_mailman

- name: Start mailman3-web (if fresh install)
  systemd:
    name: mailman3-web
    state: started
  when:
    - exim4__configure
    - exim4__use_mailman
    - mailman_stopped is changed
...
