---
# handlers file for exim4
- name: Reload aliases
  shell: "/usr/bin/newaliases"

- name: Reload exim4
  systemd:
    name: exim4
    state: reloaded

- name: Reload mm3
  systemd:
    name: mailman3
    state: reloaded
