---
# handlers file for exim4
- name: Reload aliases
  shell: "/usr/bin/newaliases"

- name: Reload exim4
  systemd:
    name: exim4
    state: reloaded

- name: Reload mm3
  systemd:
    name: mailman3
    state: reloaded

- name: Restart mm3-web
  systemd:
    name: mailman3-web
    state: restarted

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Reload AuthDaemon
  systemd:
    name: courier-authdaemon
    state: reloaded

- name: Rebuild userdb
  shell: "makeuserdb"

- name: Restart courier-imap-ssl
  systemd:
    name: courier-imap-ssl
    state: restarted

- name: Restart courier-pop-ssl
  systemd:
    name: courier-pop-ssl
    state: restarted
